# Jekyll config
title: Dastanbek Samatov
name: Dastan Samatov
email: dastanbeksamatov@gmail.com
description: Blockchain Engineer from Kyrgyzstan
url: "https://dastansam.github.io"
markdown: kramdown
highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed